# Generated by Django 5.0.3 on 2024-04-06 15:24

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pagos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cotizacion', models.IntegerField()),
                ('pay_comment', models.TextField()),
                ('pay_status', models.CharField(choices=[('Pendiente', 'Opcion 1'), ('Primer pago', 'Opcion 2'), ('Pago completo', 'Opcion 3')], max_length=20)),
                ('pay_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Sesion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ses_date', models.DateTimeField()),
                ('ses_type', models.CharField(choices=[('Boda', 'Opcion 1'), ('Bautizo', 'Opcion 2'), ('Revelacion de sexo', 'Opcion 3'), ('Cumpleaños', 'Opcion 4'), ('Quince años', 'Opcion 5'), ('Evento empresarial', 'Opcion 6')], max_length=20)),
                ('ses_comment', models.TextField()),
                ('pagos', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='formulario.pagos')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateField(default=datetime.date.today)),
                ('user_doc', models.IntegerField()),
                ('user_name', models.CharField(max_length=40)),
                ('user_email', models.EmailField(max_length=254)),
                ('user_password', models.CharField(max_length=10)),
                ('sesion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='formulario.pagos')),
            ],
        ),
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_doc', models.IntegerField()),
                ('admin_name', models.CharField(max_length=40)),
                ('admin_email', models.EmailField(max_length=254)),
                ('admin_password', models.CharField(max_length=10)),
                ('usuario', models.ManyToManyField(to='formulario.usuario')),
            ],
        ),
    ]
