# Generated by Django 5.0.4 on 2024-04-14 01:11

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Pagos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cotizacion', models.IntegerField()),
                ('pay_comment', models.TextField()),
                ('pay_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Sesion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ses_date', models.DateTimeField()),
                ('ses_comment', models.TextField()),
                ('event_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='formulario.event_type')),
                ('pagos', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='formulario.pagos')),
            ],
        ),
        migrations.AddField(
            model_name='pagos',
            name='pay_status',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='formulario.status'),
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateField(default=datetime.date.today)),
                ('user_doc', models.IntegerField()),
                ('user_name', models.CharField(max_length=40)),
                ('user_email', models.EmailField(max_length=254)),
                ('user_password', models.CharField(max_length=10)),
                ('sesion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='formulario.pagos')),
            ],
        ),
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_doc', models.IntegerField()),
                ('admin_name', models.CharField(max_length=40)),
                ('admin_email', models.EmailField(max_length=254)),
                ('admin_password', models.CharField(max_length=10)),
                ('usuario', models.ManyToManyField(to='formulario.usuario')),
            ],
        ),
    ]
