# Generated by Django 5.0.3 on 2024-04-17 07:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=30, verbose_name='Nuevo evento')),
            ],
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30, verbose_name='Nuevo estado de pago')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_doc', models.IntegerField(verbose_name='Numero de documento')),
                ('user_name', models.CharField(max_length=40, verbose_name='Nombre')),
                ('user_email', models.EmailField(max_length=254, verbose_name='Correo electronico')),
                ('user_phone', models.IntegerField(verbose_name='Numero de teléfono')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
            ],
        ),
        migrations.CreateModel(
            name='Sesion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ses_date', models.DateTimeField(verbose_name='Fecha del evento')),
                ('ses_comment', models.TextField(verbose_name='Comentarios')),
                ('cotizacion', models.IntegerField(verbose_name='Cotizacion')),
                ('pay_date', models.DateTimeField(verbose_name='Fecha de pago')),
                ('event_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='formulario.event_type', verbose_name='Tipo de evento')),
                ('pay_status', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='formulario.status', verbose_name='Estado de pago')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='formulario.usuario', verbose_name='Cliente')),
            ],
        ),
    ]
